### ISSUE TITLE
feat: Implement "Delete Record" Functionality

### ISSUE THREAD

**Issue by itsyourap** [darkard2003/cubeXtimerKotlin#1]
The app is missing the "Delete Record" which is crucial for this app.

I would like to work on it.
It would be great if you kindly assign this task to me

**Comment by darkard2003** [comment]
This app is made for the event **Apertre**. I can only accept pull requests once the event starts. I would encourage you to fork, study and improve the app meanwhile. Once the event starts, you can issue pull requests.

**Comment by itsyourap** [comment]
Yep! I am participating in Apertre. Will be waiting until it starts

**Comment by itsyourap** [comment]
@darkard2003 Since Apertre has officially started, can you assign me this issue now?

**Comment by darkard2003** [comment]
@itsyourap Sure, i will assign to you, but before that, please make sure you read CONTRIBUTING.md. Here I mentioned  every change should have its separate issue. So, make implementing delete a single issue and Delete dialog a separate issue. It's for the point distribution.

**Comment by itsyourap** [comment]
Okay! Updated the issue as per CONTRIBUTING.md
