### ISSUE TITLE
[FEAT] Informational messages when saving record

### ISSUE THREAD

**Issue by itsyourap** [darkard2003/cubeXtimerKotlin#14]
When saving a record, the save dialog should show some informational messages according to the time.

Some examples are:-
- "Congratulations! You broke all your records!" (Time < All other times)
- "You did better than your average time! Keep it up!" (Time < Average Time)
- "Perhaps you could do better! Try to solve faster!" (Time > Average Time)
- "A bit too slow! Try to solve faster next time" (Time > All other times)

I would like to implement this feature

**Comment by itsyourap** [comment]
@darkard2003 Can you assign me this issue?

**Comment by darkard2003** [comment]
Make sure you use a snackbar for this. Dialog is too intrusive and toast, I don't like toast messages.

**Comment by itsyourap** [comment]
![Screenshot_2024-01-14-22-28-44-45_596934a3d74d49f850488c59fd4cccab.jpg](https://github.com/darkard2003/cubeXtimerKotlin/assets/90060131/dcdf5f3e-1b50-4963-905e-eb3871917fc8)

What about this?

**Comment by darkard2003** [comment]
This will work too.
