### ISSUE TITLE
feat: Improve History UI look

### ISSUE THREAD

**Issue by itsyourap** [darkard2003/cubeXtimerKotlin#2]
As of now, if we don't save any records and open the history bottom sheet, the history bottom sheet does not show anything, not even "No Records", leading to the poor UX.

I would like to fix this issue and improve the look of the History UI.

Kindly please assign me this issue

**Comment by darkard2003** [comment]
Sure, go ahead and fix the UI. I am assigning this one to you. Please make sure you read CONTRIBUTING.md file.
