### ISSUE TITLE
BUG: When saving a record, Name of record should be required

### ISSUE THREAD

**Issue by itsyourap** [darkard2003/cubeXtimerKotlin#9]
Currently, when saving a record, if we supply no name to the record, it still gets saved without a name which is not a good UX.

I want to fix this issue and make the name required for saving the record.

**Comment by itsyourap** [comment]
@darkard2003 Please assign me this issue

**Comment by darkard2003** [comment]
It's by design. Sometimes I just want to save the time, not wanting to worry about names and such.

**Comment by itsyourap** [comment]
Well, we can set the name to "Untitled" by default if name is empty

Can I implement that?

**Comment by darkard2003** [comment]
Sure, you can do that

**Comment by darkard2003** [comment]
There is a bug in your code @itsyourap 

When having multiple untitled records, the "Untitled" label is not shown in the first one.

![image](https://github.com/darkard2003/cubeXtimerKotlin/assets/95243692/9f284d2a-5c92-4a8d-8ac8-c132fdb04f17)

When having multiple untitled records, the "Untitled" label is not shown in the first one.

**Comment by itsyourap** [comment]
Actually, the record was made previously (before you merged the PR) and hence the previous record did not have the Untitled label saved in the Database.
I recommend you to delete that record and create a new one without a name- It will get automatically saved in the database with the name Untitled

**Comment by darkard2003** [comment]
So, when saving, if there is no name present, you opt to use Untitled. That is a bad approach. If the user wants to keep it empty, you should save it as empty. You should only modify how it displays. While displaying the history, check if it's empty, and show untitled.
